### PR TITLE
Regex rework and adding validations for query params

### PR DESCRIPTION
**Pull request by cometman**
Cleaned up white listing regex with list of approved domains.

Added validation errors for query params when in development.

### CODE REVIEW

**Comment by ryanto** [comment]
This is 👍

**Comment by ryanto** [comment]
@cometman @celly @alexdean @redoPop - Asking because you're name is in this PR: I'd like to get this merged. Any objections?

**Comment by alexdean** [comment]
i have no opinion on whether this is ready to merge or not. haven't seen the code. sorry.

**Comment by redoPop** [comment]
Same: my name is in the PR because I added an extra domain to the whitelist to keep it parallel with the main branch.

All tests were passing when I did so, and the general approach here seems similar to [the one we've taken in js-crushinator-helpers](https://github.com/tedconf/js-crushinator-helpers/blob/master/src/crushinator.js#L18-L38), so I _think_ it's both conceptually and behaviorally sound, but @cometman knows this code's status best!

**Comment by celly** [comment]
merge it with fire.

**Comment by ryanto** [comment]
Released as 0.1.0

**Comment by danbernier** [comment]
Ah, ok. Thanks @cometman.

**Pull request merged**
